In [46]:
import os
import yfinance as yf

import pandas as pd

In [47]:
# Getting 10 years daily Dataset of Apple from Yahoo Finanace

os.makedirs("data", exist_ok=True)

# auto_adjust=False keeps the "Adj Close" column, as in your file

df = yf.download("AAPL", start="2016-9-1", end="2026-9-30", auto_adjust=False)
df.to_csv("data/AAPL.csv")
df.head()

[*********************100%***********************]  1 of 1 completed

Price       Adj Close      Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL       AAPL
Date
2016-09-01  24.407616  26.682501  26.700001  26.405001  26.535000  106806000
2016-09-02  24.636301  26.932501  27.000000  26.705000  26.924999  107210000
2016-09-06  24.629436  26.924999  27.075001  26.877501  26.975000  107521600
2016-09-07  24.780376  27.090000  27.190001  26.767500  26.957500  169457200
2016-09-08  24.130915  26.379999  26.817499  26.309999  26.812500  212008000

#### Data Loading

In [48]:
cols = ['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']
df_raw = pd.read_csv('data/AAPL.csv', skiprows=3, names=cols)

display(df_raw.shape)

display(df_raw.head())

(2532, 7)

,Date,Adj Close,Close,High,Low,Open,Volume
0,2016-09-01,24.407616,26.682501,26.700001,26.405001,26.535000,106806000
1,2016-09-02,24.636301,26.932501,27.000000,26.705000,26.924999,107210000
2,2016-09-06,24.629436,26.924999,27.075001,26.877501,26.975000,107521600
3,2016-09-07,24.780376,27.090000,27.190001,26.767500,26.957500,169457200
4,2016-09-08,24.130915,26.379999,26.817499,26.309999,26.812500,212008000

In [49]:
display(df_raw.info())

<class 'pandas.DataFrame'>
RangeIndex: 2532 entries, 0 to 2531
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2532 non-null   str
 1   Adj Close  2532 non-null   float64
 2   Close      2532 non-null   float64
 3   High       2532 non-null   float64
 4   Low        2532 non-null   float64
 5   Open       2532 non-null   float64
 6   Volume     2532 non-null   int64
dtypes: float64(5), int64(1), str(1)
memory usage: 138.6 KB

None

#### Data Cleaning

In [50]:
df = df_raw.copy()
df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d')
df = df.set_index('Date').sort_index()

num_cols = ['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']
df[num_cols] = df[num_cols].apply(pd.to_numeric, errors='coerce')

In [51]:
display(df.info())

<class 'pandas.DataFrame'>
DatetimeIndex: 2532 entries, 2016-09-01 to 2026-09-29
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Adj Close  2532 non-null   float64
 1   Close      2532 non-null   float64
 2   High       2532 non-null   float64
 3   Low        2532 non-null   float64
 4   Open       2532 non-null   float64
 5   Volume     2532 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 138.5 KB

None

In [52]:
display(df.shape)

df = df[~df.index.duplicated(keep='first')].dropna()

display(df.shape)

display(df.describe())

(2532, 6)

(2532, 6)

,Adj Close,Close,High,Low,Open,Volume
count,2532.000000,2532.000000,2532.000000,2532.000000,2532.000000,2.532000e+03
mean,132.894589,135.292450,136.648056,133.800300,135.157442,9.409442e+07
std,81.949455,81.424241,82.221519,80.537728,81.326429,5.457576e+07
min,23.584349,25.782499,26.430000,25.632500,25.662500,1.791060e+07
25%,48.161819,50.395000,50.848749,49.841249,50.244376,5.483178e+07
50%,137.556946,140.470001,142.334999,138.080002,140.294998,8.191200e+07
75%,188.232986,190.564995,191.967499,189.207497,190.365002,1.143354e+08
max,341.070007,341.070007,345.339996,338.750000,341.079987,4.479400e+08